services:
  - type: web
    name: sms-spam-classifier
    env: python
    buildCommand: "chmod +x setup.sh && ./setup.sh"
    startCommand: "streamlit run app.py --server.port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
